
'use strict';
const cfg=window.APP_CONFIG||{},$=id=>document.getElementById(id),DAY=86400000,GRACE=(cfg.OFFLINE_GRACE_DAYS||15)*DAY;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('ar',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10); const uid=()=>crypto.randomUUID();
function deviceId(){let v=localStorage.getItem('alshifaa_offline_device'); if(!v){v=crypto.randomUUID();localStorage.setItem('alshifaa_offline_device',v)} return v}
const blank={pharmacy:{name:'صيدليتي',phone:'',email:'',address:'',currency:'جنيه',expiry_warning_days:90,tax_rate:0,tax_enabled:false,invoice_footer:''},users:[{email:'admin@local',password:'12345678',role:'OWNER',full_name:'المدير',active:true}],products:[],sales:[],purchases:[],customers:[],suppliers:[],expenses:[],stock_movements:[],returns:[]};
function db(){return JSON.parse(localStorage.getItem('alshifaa_offline_db')||JSON.stringify(blank))} function saveDb(d){localStorage.setItem('alshifaa_offline_db',JSON.stringify(d))}
function lic(){return JSON.parse(localStorage.getItem('alshifaa_license')||'null')} function saveLic(x){localStorage.setItem('alshifaa_license',JSON.stringify(x))}
let state={db:db(),user:null,page:'dashboard'};
function notice(id,t,ok=false){$(id).innerHTML=`<div class="notice ${ok?'ok':'error'}">${esc(t)}</div>`}
function err(s){return ({ACTIVE:'نشط',DEVICE_MISMATCH:'الترخيص مربوط بجهاز آخر',EXPIRED:'انتهى الترخيص',SUSPENDED:'الترخيص معلق',REVOKED:'الترخيص ملغي',NOT_FOUND:'الترخيص غير موجود',BAD_REQUEST:'بيانات الترخيص ناقصة'}[s]||s)}
async function onlineLicenseCheck(key){const r=await fetch(cfg.OFFLINE_LICENSE_URL||cfg.LICENSE_CHECK_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({license_key:key,device_id:deviceId(),product_code:'PHARMACY_OFFLINE_ANDROID',client:{ua:navigator.userAgent,host:location.host}})});const x=await r.json(); if(!r.ok||!x.active)throw Error(x.status||x.error||'LICENSE_FAILED'); return x}
async function activate(){try{const key=$('activationKey').value.trim(); const x=await onlineLicenseCheck(key); saveLic({license_key:key,device_id:deviceId(),status:'ACTIVE',expires_at:x.expires_at,last_check:Date.now(),last_backup:0}); notice('activationMsg','تم التفعيل بنجاح',true); setTimeout(()=>location.reload(),700)}catch(e){notice('activationMsg',err(e.message))}}
function licenseOk(){const l=lic(); if(!l)return false; if(l.expires_at&&new Date(l.expires_at)<new Date())return false; return Date.now()-Number(l.last_check||0)<=GRACE}
async function requirePeriodic(){const l=lic(); if(!l)return false; if(Date.now()-Number(l.last_check||0)>GRACE){try{const x=await onlineLicenseCheck(l.license_key); l.status='ACTIVE'; l.expires_at=x.expires_at; l.last_check=Date.now(); saveLic(l); await uploadBackup(false); return true}catch(e){alert('يجب الاتصال بالإنترنت لتجديد الترخيص: '+err(e.message)); return false}} return true}
function table(h,rows){return `<div class="tablewrap"><table><thead><tr>${h.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${h.length}" class="empty">لا توجد بيانات</td></tr>`}</tbody></table></div>`}
async function init(){ $('activationEmail').parentElement.style.display='none'; $('activateBtn').onclick=activate; $('loginBtn').onclick=login; $('resetBtn').style.display='none'; $('licenseRefresh').onclick=manualCheck; $('logoutBtn').onclick=()=>{sessionStorage.removeItem('offline_user');location.reload()}; $('saveSettings').onclick=saveSettings; $('addProduct').onclick=()=>productForm(); $('newSale').onclick=saleForm; $('newPurchase').onclick=purchaseForm; $('newExpense').onclick=expenseForm; $('stockAdjust').onclick=adjustForm; document.body.addEventListener('click',clicks); document.querySelectorAll('#nav [data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page,b.textContent)); if(!lic()){notice('loginMsg','فعّل الترخيص أولاً. كود الجهاز: '+deviceId()); return} if(!licenseOk()){notice('loginMsg','انتهت مهلة 15 يوم. اتصل بالإنترنت واضغط فحص الترخيص.');} const u=sessionStorage.getItem('offline_user'); if(u){state.user=JSON.parse(u); if(await requirePeriodic()) openApp()} }
async function manualCheck(){try{const l=lic(); if(!l)throw Error('أدخل الترخيص أولاً'); const x=await onlineLicenseCheck(l.license_key); l.last_check=Date.now(); l.expires_at=x.expires_at; l.status='ACTIVE'; saveLic(l); await uploadBackup(true); alert('تم فحص الترخيص ورفع النسخة الاحتياطية')}catch(e){alert(err(e.message))}}
async function login(){if(!await requirePeriodic())return; const email=$('email').value.trim(),pass=$('password').value; const u=state.db.users.find(x=>x.email===email&&x.password===pass&&x.active); if(!u)return notice('loginMsg','بيانات الدخول غير صحيحة. الافتراضي admin@local / 12345678'); state.user=u; sessionStorage.setItem('offline_user',JSON.stringify(u)); openApp()}
function openApp(){$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('pharmacyTitle').textContent=state.db.pharmacy.name;$('userInfo').textContent=`${state.user.email} — ${state.user.role}`;$('licenseBadge').textContent='OFFLINE ACTIVE'; renderAll(); setInterval(()=>uploadBackup(false),60*60*1000)}
function show(id,title){state.page=id;document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');$('pageTitle').textContent=title;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id))}
function renderAll(){renderDashboard();renderProducts();renderSales();renderPurchases();renderParties('customers');renderParties('suppliers');renderExpenses();renderStock();renderReturns();renderReports();fillSettings();renderUsers()}
function renderDashboard(){const d=state.db,start=today(),rev=d.sales.filter(x=>x.created_at.slice(0,10)===start).reduce((a,x)=>a+x.total,0); $('dashboardStats').innerHTML=[['المنتجات',d.products.length],['المخزون المنخفض',d.products.filter(x=>+x.quantity<=+x.min_stock).length],['مبيعات اليوم',money(rev)],['العملاء',d.customers.length],['الموردون',d.suppliers.length]].map(v=>`<div class="stat"><span>${v[0]}</span><b>${v[1]}</b></div>`).join('')}
function renderProducts(f=''){const rows=state.db.products.filter(x=>!f||x.name.includes(f)).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.scientific_name||'')}</td><td>${esc(x.barcode||'')}</td><td>${x.quantity}</td><td>${money(x.sale_price)}</td><td>${esc(x.expiry_date||'')}</td><td><button class="btn small secondary" data-edit-product="${x.id}">تعديل</button></td></tr>`).join(''); $('productsTable').innerHTML=table(['المنتج','العلمي','الباركود','المخزون','السعر','الصلاحية',''],rows)}
function field(id,l,v='',type='text'){return `<div><label>${l}</label><input id="${id}" type="${type}" value="${esc(v)}" ${type==='number'?'step=".001"':''}></div>`}
function modal(html){$('modalContent').innerHTML=html;$('modal').classList.add('show');$('closeModal').onclick=()=>{$('modal').classList.remove('show')}}
function productForm(p={}){modal(`<h2>${p.id?'تعديل':'إضافة'} منتج</h2><div class="form-grid">${field('pName','الاسم',p.name)}${field('pSci','الاسم العلمي',p.scientific_name)}${field('pBar','الباركود',p.barcode)}${field('pQty','الكمية',p.quantity||0,'number')}${field('pCost','سعر الشراء',p.cost_price||0,'number')}${field('pPrice','سعر البيع',p.sale_price||0,'number')}${field('pMin','حد أدنى',p.min_stock||0,'number')}${field('pExp','الصلاحية',p.expiry_date||'','date')}</div><button class="btn" id="saveP">حفظ</button>`);$('saveP').onclick=()=>{let d=state.db,o=p.id?d.products.find(x=>x.id===p.id):{id:uid(),created_at:new Date().toISOString()};Object.assign(o,{name:$('pName').value,scientific_name:$('pSci').value,barcode:$('pBar').value,quantity:+$('pQty').value,cost_price:+$('pCost').value,sale_price:+$('pPrice').value,min_stock:+$('pMin').value,expiry_date:$('pExp').value,active:true}); if(!p.id)d.products.push(o); saveDb(d); state.db=d; $('modal').classList.remove('show'); renderAll()}}
function saleForm(){modal(`<h2>فاتورة بيع</h2>${field('sNo','رقم الفاتورة','S-'+Date.now())}<div><label>المنتج</label><select id="sProd">${state.db.products.map(p=>`<option value="${p.id}">${esc(p.name)} - ${p.quantity}</option>`)}</select></div>${field('sQty','الكمية',1,'number')}${field('sPaid','المدفوع',0,'number')}<button class="btn" id="saveS">حفظ</button>`);$('saveS').onclick=()=>{let d=state.db,p=d.products.find(x=>x.id===$('sProd').value),q=+$('sQty').value;if(!p||p.quantity<q)return alert('المخزون غير كاف');p.quantity-=q;let total=q*p.sale_price;d.sales.unshift({id:uid(),invoice_no:$('sNo').value,customer_name:'نقدي',total,paid:+$('sPaid').value,remaining:total-(+$('sPaid').value),created_at:new Date().toISOString(),status:'COMPLETED'});d.stock_movements.unshift({created_at:new Date().toISOString(),products:{name:p.name},movement_type:'SALE',quantity:-q,new_quantity:p.quantity});saveDb(d);state.db=d;$('modal').classList.remove('show');renderAll()}}
function purchaseForm(){modal(`<h2>فاتورة شراء</h2><div><label>المنتج</label><select id="bProd">${state.db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`)}</select></div>${field('bQty','الكمية',1,'number')}${field('bCost','التكلفة',0,'number')}<button class="btn" id="saveB">حفظ</button>`);$('saveB').onclick=()=>{let d=state.db,p=d.products.find(x=>x.id===$('bProd').value),q=+$('bQty').value;p.quantity+=q;p.cost_price=+$('bCost').value||p.cost_price;d.purchases.unshift({id:uid(),invoice_no:'P-'+Date.now(),supplier_name:'',total:q*p.cost_price,paid:0,remaining:q*p.cost_price,status:'RECEIVED',created_at:new Date().toISOString()});d.stock_movements.unshift({created_at:new Date().toISOString(),products:{name:p.name},movement_type:'PURCHASE',quantity:q,new_quantity:p.quantity});saveDb(d);state.db=d;$('modal').classList.remove('show');renderAll()}}
function invoiceHtml(x){let p=state.db.pharmacy||{};return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>فاتورة ${esc(x.invoice_no)}</title><style>*{box-sizing:border-box}body{font-family:Arial,Tahoma,sans-serif;margin:0;background:#f5f8fb;color:#17212b}.sheet{width:210mm;min-height:297mm;margin:16px auto;background:#fff;padding:16mm;box-shadow:0 6px 24px #0002}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #246b91;padding-bottom:14px}.muted{color:#71808f;font-size:12px;line-height:1.8}h1,h2{margin:0 0 8px}.box{background:#f8fbfd;border:1px solid #e3eaf0;border-radius:8px;padding:12px;margin:16px 0;display:grid;grid-template-columns:repeat(3,1fr);gap:8px}table{width:100%;border-collapse:collapse;margin-top:14px}th{background:#101826;color:white}td,th{padding:10px;border-bottom:1px solid #e3eaf0;text-align:right}.totals{width:45%;margin-right:auto;margin-top:18px;border:1px solid #e3eaf0}.totals div{display:flex;justify-content:space-between;padding:10px 12px;border-bottom:1px solid #e3eaf0}.footer{text-align:center;color:#71808f;border-top:1px solid #e3eaf0;margin-top:40px;padding-top:14px;font-size:12px}@media(max-width:800px){.sheet{width:100%;min-height:auto;margin:0;padding:14px}.box{grid-template-columns:1fr}.totals{width:100%}}@media print{body{background:white}.sheet{box-shadow:none;margin:0;width:100%;min-height:auto}@page{size:A4;margin:8mm}}</style></head><body><main class="sheet"><section class="head"><div><h1>${esc(p.name||'الصيدلية')}</h1><div class="muted">${esc(p.address||'')}<br>${esc(p.phone||'')} ${p.email?' — '+esc(p.email):''}</div></div><div><h2>فاتورة بيع</h2><div class="muted">رقم الفاتورة: ${esc(x.invoice_no)}<br>التاريخ: ${esc((x.created_at||'').slice(0,10))}<br>الحالة: ${esc(x.status||'')}</div></div></section><section class="box"><div>العميل: <b>${esc(x.customer_name||'نقدي')}</b></div><div>طريقة الدفع: <b>نقدي</b></div><div>العملة: <b>${esc(p.currency||'جنيه')}</b></div></section><table><thead><tr><th>#</th><th>الصنف</th><th>الإجمالي</th></tr></thead><tbody><tr><td>1</td><td>فاتورة بيع</td><td>${money(x.total)}</td></tr></tbody></table><section class="totals"><div><span>الإجمالي</span><b>${money(x.total)} ${esc(p.currency||'')}</b></div><div><span>المدفوع</span><span>${money(x.paid)}</span></div><div><span>المتبقي</span><span>${money(x.remaining)}</span></div></section><div class="footer">${esc(p.invoice_footer||'شكراً لتعاملكم معنا')}</div></main></body></html>`}
function previewInvoice(id){let x=state.db.sales.find(s=>s.id===id);if(!x)return alert('الفاتورة غير موجودة');let old=document.getElementById('invoicePreview');if(old)old.remove();let wrap=document.createElement('div');wrap.id='invoicePreview';wrap.className='invoice-preview no-print';wrap.innerHTML='<div class="invoice-toolbar"><button class="btn" id="doInvoicePrint">طباعة الفاتورة</button><button class="btn secondary" id="closeInvoicePreview">إغلاق</button></div><iframe title="معاينة الفاتورة"></iframe>';document.body.appendChild(wrap);let frame=wrap.querySelector('iframe');frame.srcdoc=invoiceHtml(x);document.getElementById('closeInvoicePreview').onclick=()=>wrap.remove();document.getElementById('doInvoicePrint').onclick=()=>{frame.contentWindow.focus();frame.contentWindow.print()}}
function renderSales(){$('salesTable').innerHTML=table(['الفاتورة','التاريخ','العميل','الإجمالي','المدفوع','المتبقي','الحالة','إجراءات'],state.db.sales.map(x=>`<tr><td>${x.invoice_no}</td><td>${x.created_at.slice(0,10)}</td><td>${x.customer_name}</td><td>${money(x.total)}</td><td>${money(x.paid)}</td><td>${money(x.remaining)}</td><td>${x.status}</td><td><button class="btn small secondary" data-print-sale="${x.id}">عرض/طباعة</button></td></tr>`).join(''))} 
function renderPurchases(){$('purchasesTable').innerHTML=table(['الفاتورة','التاريخ','المورد','الإجمالي','المدفوع','المتبقي','الحالة'],state.db.purchases.map(x=>`<tr><td>${x.invoice_no}</td><td>${x.created_at.slice(0,10)}</td><td>${x.supplier_name}</td><td>${money(x.total)}</td><td>${money(x.paid)}</td><td>${money(x.remaining)}</td><td>${x.status}</td></tr>`).join(''))}
function renderParties(k){$(`${k}Table`).innerHTML=table([k==='customers'?'العميل':'المورد','الهاتف','الرصيد'],state.db[k].map(x=>`<tr><td>${x.name}</td><td>${x.phone||''}</td><td>${money(x.current_balance)}</td></tr>`).join(''))}
function expenseForm(){modal(`<h2>إضافة مصروف</h2>${field('eTitle','الوصف')}${field('eAmount','المبلغ',0,'number')}<button class="btn" id="saveE">حفظ</button>`);$('saveE').onclick=()=>{let d=state.db;d.expenses.unshift({title:$('eTitle').value,amount:+$('eAmount').value,expense_date:today(),payment_method:'CASH'});saveDb(d);state.db=d;$('modal').classList.remove('show');renderAll()}}
function renderExpenses(){$('expensesTable').innerHTML=table(['التاريخ','الوصف','المبلغ','الدفع'],state.db.expenses.map(x=>`<tr><td>${x.expense_date}</td><td>${x.title}</td><td>${money(x.amount)}</td><td>${x.payment_method}</td></tr>`).join(''))}
function adjustForm(){modal(`<h2>تسوية مخزون</h2><div><label>المنتج</label><select id="aProd">${state.db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`)}</select></div>${field('aQty','الكمية +/-',0,'number')}<button class="btn" id="saveA">حفظ</button>`);$('saveA').onclick=()=>{let d=state.db,p=d.products.find(x=>x.id===$('aProd').value),q=+$('aQty').value;p.quantity+=q;d.stock_movements.unshift({created_at:new Date().toISOString(),products:{name:p.name},movement_type:'ADJUSTMENT',quantity:q,new_quantity:p.quantity});saveDb(d);state.db=d;$('modal').classList.remove('show');renderAll()}}
function renderStock(){$('stockTable').innerHTML=table(['التاريخ','المنتج','النوع','الحركة','بعد'],state.db.stock_movements.map(x=>`<tr><td>${x.created_at.slice(0,10)}</td><td>${x.products?.name||''}</td><td>${x.movement_type}</td><td>${x.quantity}</td><td>${x.new_quantity}</td></tr>`).join(''))}
function renderReturns(){$('returnsTable').innerHTML=table(['الرقم','النوع','الإجمالي','التاريخ'],state.db.returns.map(x=>`<tr><td>${x.return_no}</td><td>${x.return_type}</td><td>${money(x.total)}</td><td>${x.created_at}</td></tr>`).join(''))}
function renderReports(){let revenue=state.db.sales.reduce((a,x)=>a+x.total,0),exp=state.db.expenses.reduce((a,x)=>a+x.amount,0);$('reportsBody').innerHTML=`<div class="stats"><div class="stat"><span>إجمالي المبيعات</span><b>${money(revenue)}</b></div><div class="stat"><span>المصروفات</span><b>${money(exp)}</b></div><div class="stat"><span>الصافي</span><b>${money(revenue-exp)}</b></div></div>`}
function fillSettings(){let p=state.db.pharmacy; ['Name','Phone','Email','Address','Currency'].forEach(k=>{let el=$('set'+k); if(el)el.value=p[k.toLowerCase()]||''});$('setTax').value=p.tax_rate||0;$('setExpiry').value=p.expiry_warning_days||90;$('setFooter').value=p.invoice_footer||''}
function saveSettings(){let d=state.db,p=d.pharmacy;p.name=$('setName').value;p.phone=$('setPhone').value;p.email=$('setEmail').value;p.address=$('setAddress').value;p.currency=$('setCurrency').value;p.tax_rate=+$('setTax').value;p.expiry_warning_days=+$('setExpiry').value;p.invoice_footer=$('setFooter').value;saveDb(d);state.db=d;notice('settingsMsg','تم الحفظ',true);openApp()}
function renderUsers(){$('usersTable').innerHTML=table(['الاسم','البريد','الدور'],state.db.users.map(u=>`<tr><td>${u.full_name}</td><td>${u.email}</td><td>${u.role}</td></tr>`).join(''))}
function clicks(e){let pr=e.target.closest('[data-print-sale]'); if(pr)previewInvoice(pr.dataset.printSale); let ep=e.target.closest('[data-edit-product]'); if(ep)productForm(state.db.products.find(x=>x.id===ep.dataset.editProduct)); let j=e.target.closest('[data-jump]'); if(j){let n=document.querySelector(`#nav [data-page="${j.dataset.jump}"]`); if(n)n.click()}}
async function uploadBackup(force){const l=lic(); if(!l||!cfg.OFFLINE_BACKUP_URL)return; if(!force&&Date.now()-Number(l.last_backup||0)<GRACE)return; try{let backup={created_at:new Date().toISOString(),device_id:deviceId(),data:state.db}; let r=await fetch(cfg.OFFLINE_BACKUP_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({license_key:l.license_key,device_id:deviceId(),backup})}); let x=await r.json(); if(r.ok&&x.ok){l.last_backup=Date.now();saveLic(l)}}catch(e){} }
init();
